#pragma once

struct keycodes {
    /* Printable keys */
    static constexpr int space = 32;
    static constexpr int apostrophe = 39;  /* ' */
    static constexpr int comma = 44;  /* , */
    static constexpr int minus = 45;  /* - */
    static constexpr int period = 46;  /* . */
    static constexpr int slash = 47;  /* / */
    static constexpr int num0 =48;
    static constexpr int num1 =49;
    static constexpr int num2 =50;
    static constexpr int num3 =51;
    static constexpr int num4 =52;
    static constexpr int num5 =53;
    static constexpr int num6 =54;
    static constexpr int num7 =55;
    static constexpr int num8 =56;
    static constexpr int num9 =57;
    static constexpr int semicolon = 59;  /* ; */
    static constexpr int equal = 61;  /* = */
    static constexpr int a = 65;
    static constexpr int b = 66;
    static constexpr int c = 67;
    static constexpr int d = 68;
    static constexpr int e = 69;
    static constexpr int f = 70;
    static constexpr int g = 71;
    static constexpr int h = 72;
    static constexpr int i = 73;
    static constexpr int j = 74;
    static constexpr int k = 75;
    static constexpr int l = 76;
    static constexpr int m = 77;
    static constexpr int n = 78;
    static constexpr int o = 79;
    static constexpr int p = 80;
    static constexpr int q = 81;
    static constexpr int r = 82;
    static constexpr int s = 83;
    static constexpr int t = 84;
    static constexpr int u = 85;
    static constexpr int v = 86;
    static constexpr int w = 87;
    static constexpr int x = 88;
    static constexpr int y = 89;
    static constexpr int z = 90;
    static constexpr int leftBracket = 91;  /* [ */
    static constexpr int backslash = 92;  /* \ */
    static constexpr int rightBracket = 93;  /* ] */
    static constexpr int graveAccent = 96;  /* ` */
    static constexpr int world1 = 161; /* non-US #1 */
    static constexpr int world2 = 162; /* non-US #2 */

    /* Function keys */
    static constexpr int escape = 256;
    static constexpr int enter = 257;
    static constexpr int tab = 258;
    static constexpr int backspace = 259;
    static constexpr int insert = 260;
    static constexpr int del = 261;
    static constexpr int right = 262;
    static constexpr int left = 263;
    static constexpr int down = 264;
    static constexpr int up = 265;
    static constexpr int pageUp = 266;
    static constexpr int pageDown = 267;
    static constexpr int home = 268;
    static constexpr int end = 269;
    static constexpr int capsLock = 280;
    static constexpr int scrollLock = 281;
    static constexpr int numLock = 282;
    static constexpr int printScreen = 283;
    static constexpr int pause = 284;
    static constexpr int f1 =290;
    static constexpr int f2 =291;
    static constexpr int f3 =292;
    static constexpr int f4 =293;
    static constexpr int f5 =294;
    static constexpr int f6 =295;
    static constexpr int f7 =296;
    static constexpr int f8 =297;
    static constexpr int f9 =298;
    static constexpr int f10 = 299;
    static constexpr int f11 = 300;
    static constexpr int f12 = 301;
    static constexpr int f13 = 302;
    static constexpr int f14 = 303;
    static constexpr int f15 = 304;
    static constexpr int f16 = 305;
    static constexpr int f17 = 306;
    static constexpr int f18 = 307;
    static constexpr int f19 = 308;
    static constexpr int f20 = 309;
    static constexpr int f21 = 310;
    static constexpr int f22 = 311;
    static constexpr int f23 = 312;
    static constexpr int f24 = 313;
    static constexpr int f25 = 314;
    static constexpr int kp0 = 320;
    static constexpr int kp1 = 321;
    static constexpr int kp2 = 322;
    static constexpr int kp3 = 323;
    static constexpr int kp4 = 324;
    static constexpr int kp5 = 325;
    static constexpr int kp6 = 326;
    static constexpr int kp7 = 327;
    static constexpr int kp8 = 328;
    static constexpr int kp9 = 329;
    static constexpr int kpDecimal = 330;
    static constexpr int kpDivide = 331;
    static constexpr int kpMultiply = 332;
    static constexpr int kpSubtract = 333;
    static constexpr int kpAdd = 334;
    static constexpr int kpEnter = 335;
    static constexpr int kpEqual = 336;
    static constexpr int leftShift = 340;
    static constexpr int leftControl = 341;
    static constexpr int leftAlt = 342;
    static constexpr int leftSuper = 343;
    static constexpr int rightShift = 344;
    static constexpr int rightControl = 345;
    static constexpr int rightAlt = 346;
    static constexpr int rightSuper = 347;
    static constexpr int menu = 348;
    static constexpr int last = menu;
    static constexpr int windows = leftSuper;
    static constexpr int cmd = leftSuper;
};

inline keycodes key;